/* Generated by Babel */
'use strict';

var React = require('react');
var ReactDOMServer = require('react-dom/server');
var createReactClass = require('create-react-class');

var MyComponent = createReactClass({
    render: function render() {
        return React.createElement(
            'div',
            null,
            React.createElement(
                'h1',
                null,
                'React Component on Server'
            ),
            React.createElement(
                'p',
                null,
                'Yes, it is happening!!!'
            )
        );
    }
});

module.exports.MyComponent = MyComponent;