/* Generated by Babel */
"use strict";

var HelloMessage = React.createClass({
    displayName: "HelloMessage",

    sayMessage: function sayMessage() {
        console.log(this.props.children);
    },
    render: function render() {
        return React.createElement(
            "div",
            null,
            React.createElement(
                "h3",
                null,
                "Hello ",
                this.props.word
            ),
            React.createElement(
                "a",
                { href: "#", onClick: this.sayMessage },
                "Click for Message!"
            )
        );
    }
});

ReactDOM.render(React.createElement(
    HelloMessage,
    { word: "Everyone se guarda???!!!" },
    "This is React Shitposting"
), document.getElementById('HelloMessage'));