/* Generated by Babel */
"use strict";

var AlertBox = React.createClass({
    displayName: "AlertBox",

    render: function render() {
        return React.createElement(
            "div",
            { className: "alert alert-" + this.props.type },
            this.props.children
        );
    }
});

var RegForm = React.createClass({
    displayName: "RegForm",

    getInitialState: function getInitialState() {
        return {
            showAlert: false
        };
    },
    register: function register(e) {
        e.preventDefault();
        var firstName = this.refs.firstName.value.trim();
        var lastName = this.refs.lastName.value.trim();
        var email = this.refs.email.value.trim();

        if (!firstName || !lastName || !email) {
            this.setState({ showAlert: true });
            return;
        }

        this.setState({ showAlert: false });
        console.log(firstName);
        console.log(lastName);
        console.log(email);
    },
    render: function render() {
        return React.createElement(
            "form",
            { onSubmit: this.register },
            this.state.showAlert ? React.createElement(
                AlertBox,
                { type: "danger" },
                "Please submit all fields a**hole!!"
            ) : null,
            React.createElement(
                "div",
                { className: "form-group" },
                React.createElement(
                    "label",
                    { htmlFor: "firstName" },
                    "First Name:"
                ),
                React.createElement("input", { type: "text", className: "form-control", placeholder: "First Name", ref: "firstName" })
            ),
            React.createElement(
                "div",
                { className: "form-group" },
                React.createElement(
                    "label",
                    { htmlFor: "lastName" },
                    "Last Name:"
                ),
                React.createElement("input", { type: "text", className: "form-control", placeholder: "Last Name", ref: "lastName" })
            ),
            React.createElement(
                "div",
                { className: "form-group" },
                React.createElement(
                    "label",
                    { htmlFor: "email" },
                    "E-mail:"
                ),
                React.createElement("input", { type: "email", className: "form-control", placeholder: "E-mail", ref: "email" })
            ),
            React.createElement(
                "div",
                { className: "form-group" },
                React.createElement("input", { type: "submit", className: "btn btn-primary btn-block", value: "Submit" })
            )
        );
    }
});

ReactDOM.render(React.createElement(RegForm, null), document.getElementById('regform'));