/* Generated by Babel */
"use strict";

var Nav = React.createClass({
    displayName: "Nav",

    getInitialState: function getInitialState() {
        return { current: 0 };
    },
    clicked: function clicked(m, index) {
        this.setState({ current: index });
        console.log(m);
    },
    render: function render() {
        var self = this;
        return React.createElement(
            "ul",
            { className: "nav navbar-nav" },
            self.props.menuItems.map(function (m, index) {

                var style = self.state.current == index ? "active" : "";

                return React.createElement(
                    "li",
                    { className: style, key: m.toString() },
                    React.createElement(
                        "a",
                        { href: "#", onClick: self.clicked.bind(self, m, index) },
                        m
                    )
                );
            })
        );
    }
});

ReactDOM.render(React.createElement(Nav, { menuItems: ['Home', 'About', 'Services', 'Contact'] }), document.getElementById('nav'));